- hosts: localhost
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  roles:
  - role: apache2
    tags: 
    - install_apache
  - role: mysql
    tags: 
    - install_mysql
    vars:
    mysql_root_password: "mypass"
  - role: php
    tags: 
    - intstall_php
  - role : postfix-ses
    tags: 
    - install_postfix_ses
    vars:  
    postfix_aliases:
      - user: root
        alias: 
    postfix_relayhost: 
    postfix_relaytls: true
    # AWS IAM SES credentials (not access key):
    postfix_sasl_user: 
    postfix_sasl_password: 
