- name: Install Php and php library 
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
   - php
   - php-gd
   - php-curl
   - php-mysql
   - php-dom
   - php-xml

- name: Restart Apache
  service:
    name: apache2
    state: restarted